mongodb:
  image: mongo
  container_name: mongo-bitcore-testnet
  ports:
    - "3503:27017"
  volumes:
    - ../data:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always

bitcore-node-testnet:
  build: .
  dockerfile: Dockerfile
  container_name: bitcore-node-testnet
  links:
    - mongodb
  ports:
    - "3004:3000"
  restart: always
